name: 打包并生成Docker镜像
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
jobs:
  package-and-make-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: 
          - linux
        arch:
          - amd64
          - arm64
          - arm/v7
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: 登陆DockerHub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKER_USER_NAME }}
            password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: 获取标签名称
        id: read-docker-image-identifiers
        run: |
          if [ -n "${{ steps.version_step.outputs.version_tag }}" ]; then
            echo VERSION_TAG=$(echo ${{ steps.version_step.outputs.version_tag }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
      - name: 构建通过打标签构建的镜像
        # 如果$GITHUB_ENV中的VERSION_TAG存在
        if: env.VERSION_TAG != ''
        uses: docker/build-push-action@v2
        with:
          platforms: 
            ${{ matrix.os }}/${{matrix.arch}}
          context: .
          push: true
          tags: |
            maodou38/${{ github.event.repository.name }}:latest
            maodou38/${{ github.event.repository.name }}:${{ env.VERSION_TAG }}
      - name: 构建手动触发的镜像
        # 如果$GITHUB_ENV中的VERSION_TAG不存在
        if: env.VERSION_TAG == ''
        uses: docker/build-push-action@v2
        with:
          platforms:
            ${{ matrix.os }}/${{matrix.arch}}
          context: .
          push: true
          tags: |
            maodou38/${{ github.event.repository.name }}:latest